// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.


const randint = (val) => {
  return Math.floor(Math.random() * val);
};
const findTheDifference = (s, t) => {
  let map_s = new Map();
  let map_t = new Map();
  //for loop to mapping the s String
  for (let i = 0; i < s.length; i++) {
    if (!map_s.has(s[i])) {
      map_s.set(s[i], 1);
    } else {
      map_s.set(s[i], map_s.get(s[i]) + 1);
    }
  }
  //second loop to mapping the t string. this loop is for cases that the is more then one occurence in s
  for (let i = 0; i < t.length; i++) {
    if (!map_t.has(t[i])) {
      map_t.set(t[i], 1);
    } else {
      map_t.set(t[i], map_t.get(t[i]) + 1);
    }
  }
  console.log(map_s);
  //this loop run over t to find the difference between s and t
  for (let i = 0; i < t.length; i++) {
    if (!map_s.has(t[i])) {
      //this simple case if the t[i] is not in s at all
      return t[i];
    } else {
      if (map_s.get(t[i]) !== map_t.get(t[i])) {
        //this case is if there is case like this s="a"; t="aa"
        return t[i];
      }
    }
  }
};

//--------------------main----------------------------------------------------
console.log(findTheDifference("y", "yy"));
